base_url = "https://adriansieber.com"
title = "Adrian Sieber's Website"
description = "Adrian Sieber's personal website and blog"
default_language = "en"

# The site theme to use.
# theme = ""

generate_feed = true
compile_sass = true

taxonomies = [{name = "tags"}]

[markdown]
highlight_code = true
highlight_theme = "monokai"
